version: '3.1'
services:
  test-db:
    image: postgres
    restart: always
    volumes:
      - ./docker-data/test-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - 5433:5432
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker-data/cookbook-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  api:
    image: cookbook-api
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/app/src
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 9090:8080
